# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'מוקד שרפ' do
  # Use static libraries instead of dynamic frameworks to avoid
  # Hebrew character encoding issues in framework names during CI builds
  use_frameworks! :linkage => :static

  # Add the pod for Firebase Cloud Messaging
  pod 'Firebase/Messaging'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      # Build as static library
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end